### ISSUE TITLE
React Native Scanner

### ISSUE THREAD

**Issue by ekryski** [bitrise-io/steps-repository-scanner#11]
Would be great to be able to detect if the project was a React Native app and set up the workflow accordingly.

Off the top of my head for detection:
- [ ] Look for `index.ios.js` or `index.android.js`
- [ ] Look for `package.json`

Steps to set up:
- [ ] activate ssh key
- [ ] git clone repo
- [ ] `npm install`
- [ ] `npm test` (maybe)
- [ ]  Install react native
- [ ]  react native bundle
- [ ]  if Android drop into Gradle detector
- [ ] if iOS drop into iOS detector

**Comment by viktorbenei** [comment]
Awesome, thank you for the details! We definitely plan to add RN support to the scanner in the near future, your list will help a lot! 😉

**Comment by callmephilip** [comment]
I've stumbled upon a really annoying issue while RN + fastlane setup. When RN packager is run at the end of the build process, if it fails for some reason (error in your code, missing files), you end up with a cryptic error message from xcode which looks smth like this:

```
The following build commands failed: 
PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/vagrant/Library/Developer/Xcode/DerivedData/PokemonMap-hitodhodyhmznpfhbsqsddrmkusj/Build/Intermediates/ArchiveIntermediates/PokemonMap/IntermediateBuildFilesPath/PokemonMap.build/Release-iphoneos/PokemonMap.build/Script-00DD1BFF1BD5951E006B06BC.sh 
(1 failure) 
[12:09:27]: Exit status: 65
```

it would be great to be able to have more context on this: either prerun the bundler to see if everything is ok or make sure that PhaseScriptExecution spits out some info regarding what went down

**Comment by viktorbenei** [comment]
Sorry @callmephilip , but how is this related to the scanner / to this repository? I might be wrong, but you most likely get the error from the Fastlane step, so you should create a bug report there instead. Let me know if I'm mistaken and your comment should actually be here.

**Comment by callmephilip** [comment]
@godrei pointed me here to share my experience with RN + Fastlane on Bitrise saying it might be useful. I guess what I was trying to suggest is that verifying RN bundler is working would be a cool feature in the scanner 😄

**Comment by viktorbenei** [comment]
@callmephilip I see, no problem at all.

Re: your bug report: it seems that this is related to `fastlane` itself, its own output formatter what omits details in this case, so you should create a bug report on their GitHub page https://github.com/fastlane/fastlane

Re: verifying RN bundler is working: it's a bit out of scope right now, and I'm not sure if that's sensible to do at all. The problem is: the scanner can run on any platform, e.g. on Linux where Xcode is not available, or on Mac OS platform where another Xcode is installed, not the one your project requires. So, at least for now, the scanner's purpose is to try to generate a sensible configuration which then, if executed on the **right** platform, will produce a successful build for you.

There are other issues with verifying whether bundler or any other tools works, during the scan, e.g. what should it do if it does not? Our current practice is to try to generate the best starter workflow with the scanner, so that you can run a build. If it fails, there you can change your settings, the environment or anything else. If the scanner itself would not allow your project to be configured, e.g. because of a configuration issue in your fastlane file or anywhere else, all you could do is to start the process over and over again, without having any control over the environment or configuration.

Personally I think that the scanner should remain as it is today, a tool which tries to detect certain requirements (as many as possible) and provide the required information (environment & configuration) so that your build will pass. If it does not pass, then you have full control over fixing / changing things.

Does that make sense? Would you still implement the check in the scanner? If yes, what should happen if the validation can't pass (e.g. you forgot to include a crucial file in your repository)?

**Comment by callmephilip** [comment]
@viktorbenei : yeah thanks for the clarifications. i think this does make sense. making fastlane more verbose with PhaseScriptExecution is what needs to be done here

**Comment by viktorbenei** [comment]
@callmephilip I agree, that would improve the process / help you to get your first green build when you have an issue like the one you reported. Could you please create a bug report on their GitHub? They're usually quite fast to fix/change things.
